# This file was generated by GoReleaser. DO NOT EDIT.
class Kubemqctl < Formula
  desc ""
  homepage ""
  version "2.0.0rc1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kubemq-io/kubemqctl/releases/download/v2.0.0rc1/kubemqctl_2.0.0rc1_darwin_amd64.tar.gz"
    sha256 "e3acffbf21fc69a521b1df38359df311f81f2c62469000b3de3f34fef1f17987"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kubemq-io/kubemqctl/releases/download/v2.0.0rc1/kubemqctl_2.0.0rc1_linux_amd64.tar.gz"
      sha256 "3dab8db0c959ee8715da8230bcf4f49be89781d5bd4607ad68f350dc0094f436"
    end
  end

  def install
    bin.install "kubemqctl"
  end
end
